//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace URM.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using log4net;
    
    public partial class URMEntities : DbContext
    {
    	 /// <summary>
         ///     The log.
         /// </summary>
         protected static readonly ILog log = LogManager.GetLogger(typeof(URMEntities));
    
        public URMEntities(string connectionString) :
            base(new System.Data.Entity.Core.Objects.ObjectContext(new System.Data.Entity.Core.EntityClient.EntityConnection(connectionString), true),true)
        {
    		base.Database.Log = s => log.Info(s);
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppInfo> AppInfo { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<UserAccount> UserAccount { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
    }
}
