//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppInfo
    {
        public AppInfo()
        {
            this.Roles = new HashSet<Role>();
            this.Groups = new HashSet<Group>();
            this.UserInfoes = new HashSet<UserInfo>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Role> Roles { get; set; }
        public virtual ICollection<Group> Groups { get; set; }
        public virtual ICollection<UserInfo> UserInfoes { get; set; }
    }
}
