//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleLink
    {
        public int Id { get; set; }
        public string URL { get; set; }
        public string Target { get; set; }
    
        public virtual Article Article { get; set; }
    }
}
