//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleLanguage
    {
        public int ArticleId { get; set; }
        public string LanguageId { get; set; }
        public string Title { get; set; }
        public string Brief { get; set; }
        public string Contents { get; set; }
    
        public virtual Article Article { get; set; }
    }
}
