//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attribute
    {
        public Attribute()
        {
            this.ProductAttributes = new HashSet<ProductAttribute>();
        }
    
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public int Orders { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ICollection<ProductAttribute> ProductAttributes { get; set; }
    }
}
