//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Articles = new HashSet<Article>();
            this.CategoryLanguages = new HashSet<CategoryLanguage>();
            this.CategoryMaps = new HashSet<CategoryMap>();
            this.SupportOnlines = new HashSet<SupportOnline>();
        }
    
        public int Id { get; set; }
        public string TypeId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Image { get; set; }
    
        public virtual ICollection<Article> Articles { get; set; }
        public virtual CategoryType CategoryType { get; set; }
        public virtual Item Item { get; set; }
        public virtual ICollection<CategoryLanguage> CategoryLanguages { get; set; }
        public virtual ICollection<CategoryMap> CategoryMaps { get; set; }
        public virtual ICollection<SupportOnline> SupportOnlines { get; set; }
    }
}
