//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryMap
    {
        public int CMId { get; set; }
        public int CategoryId { get; set; }
        public bool IsAccept { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual CategoryFix CategoryFix { get; set; }
    }
}
