//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyUser
    {
        public int CompanyId { get; set; }
        public int UserId { get; set; }
        public decimal Balance { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
