//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.Attributes = new HashSet<Attribute>();
            this.BanIPs = new HashSet<BanIP>();
            this.Customers = new HashSet<Customer>();
            this.CompanyAddresses = new HashSet<CompanyAddress>();
            this.CompanyDomains = new HashSet<CompanyDomain>();
            this.CompanyLanguages = new HashSet<CompanyLanguage>();
            this.CompanyTemplates = new HashSet<CompanyTemplate>();
            this.CompanyUsers = new HashSet<CompanyUser>();
            this.Items = new HashSet<Item>();
            this.MenuShortcuts = new HashSet<MenuShortcut>();
            this.Orders1 = new HashSet<Order>();
            this.Suppliers = new HashSet<Supplier>();
            this.TB_ThongKe = new HashSet<TB_ThongKe>();
            this.TemplateConfigs = new HashSet<TemplateConfig>();
            this.WarehouseIOs = new HashSet<WarehouseIO>();
        }
    
        public int Id { get; set; }
        public string RefId { get; set; }
        public string Email { get; set; }
        public string Image { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string WardId { get; set; }
        public string DistrictId { get; set; }
        public int Orders { get; set; }
        public bool IsDemo { get; set; }
        public bool IsWholesale { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyByUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateByUser { get; set; }
        public bool IsConfirm { get; set; }
    
        public virtual ICollection<Attribute> Attributes { get; set; }
        public virtual ICollection<BanIP> BanIPs { get; set; }
        public virtual District District { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<CompanyAddress> CompanyAddresses { get; set; }
        public virtual ICollection<CompanyDomain> CompanyDomains { get; set; }
        public virtual ICollection<CompanyLanguage> CompanyLanguages { get; set; }
        public virtual ICollection<CompanyTemplate> CompanyTemplates { get; set; }
        public virtual ICollection<CompanyUser> CompanyUsers { get; set; }
        public virtual ICollection<Item> Items { get; set; }
        public virtual ICollection<MenuShortcut> MenuShortcuts { get; set; }
        public virtual ICollection<Order> Orders1 { get; set; }
        public virtual ICollection<Supplier> Suppliers { get; set; }
        public virtual ICollection<TB_ThongKe> TB_ThongKe { get; set; }
        public virtual ICollection<TemplateConfig> TemplateConfigs { get; set; }
        public virtual ICollection<WarehouseIO> WarehouseIOs { get; set; }
        public virtual WebConfig WebConfig { get; set; }
    }
}
