//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAddress
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public bool IsDefault { get; set; }
        public string AreaId { get; set; }
        public string AreaName { get; set; }
        public string Addresss { get; set; }
        public string Phone { get; set; }
        public string Name { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
