//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.UserInfoes = new HashSet<UserInfo>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Roles { get; set; }
        public int AppId { get; set; }
    
        public virtual AppInfo AppInfo { get; set; }
        public virtual ICollection<UserInfo> UserInfoes { get; set; }
    }
}
