//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int WarehouseId { get; set; }
        public string ProductCode { get; set; }
        public int Stock { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
