//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.ItemComments = new HashSet<ItemComment>();
            this.ItemImages = new HashSet<ItemImage>();
            this.Customers = new HashSet<Customer>();
        }
    
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public int Orders { get; set; }
        public bool IsPublished { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public int ModifyByUser { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ThirdParty ThirdParty { get; set; }
        public virtual Article Article { get; set; }
        public virtual Category Category { get; set; }
        public virtual AttributeCategory AttributeCategory { get; set; }
        public virtual AttributeValue AttributeValue { get; set; }
        public virtual ItemComment ItemComment { get; set; }
        public virtual ICollection<ItemComment> ItemComments { get; set; }
        public virtual ICollection<ItemImage> ItemImages { get; set; }
        public virtual ItemLike ItemLike { get; set; }
        public virtual ItemView ItemView { get; set; }
        public virtual ItemVote ItemVote { get; set; }
        public virtual ModuleConfig ModuleConfig { get; set; }
        public virtual SupportOnline SupportOnline { get; set; }
        public virtual Voucher Voucher { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
