//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuShortcut
    {
        public int Id { get; set; }
        public int ParentId { get; set; }
        public int CategoryId { get; set; }
        public string CategoryType { get; set; }
        public int CompanyId { get; set; }
        public string Name { get; set; }
        public int No { get; set; }
        public bool IsCategories { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
