//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        public Module()
        {
            this.ModuleConfigs = new HashSet<ModuleConfig>();
            this.ModuleParams = new HashSet<ModuleParam>();
            this.TemplateSkins = new HashSet<TemplateSkin>();
        }
    
        public string ModuleName { get; set; }
        public string Summary { get; set; }
    
        public virtual ICollection<ModuleConfig> ModuleConfigs { get; set; }
        public virtual ICollection<ModuleParam> ModuleParams { get; set; }
        public virtual ICollection<TemplateSkin> TemplateSkins { get; set; }
    }
}
