//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleConfigParam
    {
        public int ModuleId { get; set; }
        public string ParamName { get; set; }
        public string Value { get; set; }
    
        public virtual ModuleConfig ModuleConfig { get; set; }
    }
}
