//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.CustomerPoints = new HashSet<CustomerPoint>();
            this.OrderProducts = new HashSet<OrderProduct>();
            this.OrderTransactions = new HashSet<OrderTransaction>();
        }
    
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public int ShippingId { get; set; }
        public string ShippingCode { get; set; }
        public int Status { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerEmail { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerPhone { get; set; }
        public string CustomerNote { get; set; }
        public decimal CustomerPayDelivery { get; set; }
        public string Note { get; set; }
        public decimal Due { get; set; }
        public decimal DeliveryFee { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<System.DateTime> ConfirmDate { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public bool IsPaid { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public string Voucher { get; set; }
        public Nullable<decimal> Point { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ICollection<CustomerPoint> CustomerPoints { get; set; }
        public virtual ICollection<OrderProduct> OrderProducts { get; set; }
        public virtual ICollection<OrderTransaction> OrderTransactions { get; set; }
    }
}
