//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ProductColors = new HashSet<ProductColor>();
            this.OrderProducts = new HashSet<OrderProduct>();
            this.ProductAddOns = new HashSet<ProductAddOn>();
            this.ProductAddOns1 = new HashSet<ProductAddOn>();
            this.ProductAttributes = new HashSet<ProductAttribute>();
            this.ProductPrices = new HashSet<ProductPrice>();
            this.WarehouseIOColections = new HashSet<WarehouseIOColection>();
        }
    
        public int Id { get; set; }
        public decimal Price { get; set; }
        public decimal Sale { get; set; }
        public string Code { get; set; }
        public int Quantity { get; set; }
        public int SaleMin { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual ICollection<ProductColor> ProductColors { get; set; }
        public virtual ICollection<OrderProduct> OrderProducts { get; set; }
        public virtual ICollection<ProductAddOn> ProductAddOns { get; set; }
        public virtual ICollection<ProductAddOn> ProductAddOns1 { get; set; }
        public virtual ICollection<ProductAttribute> ProductAttributes { get; set; }
        public virtual ProductGroupon ProductGroupon { get; set; }
        public virtual ICollection<ProductPrice> ProductPrices { get; set; }
        public virtual ICollection<WarehouseIOColection> WarehouseIOColections { get; set; }
    }
}
