//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEO
    {
        public int Id { get; set; }
        public string SEOURL { get; set; }
        public int CompanyId { get; set; }
        public string LanguageId { get; set; }
        public Nullable<int> RefItem { get; set; }
        public string URL { get; set; }
        public string MetaKeyWork { get; set; }
        public string MetaDescription { get; set; }
        public string Title { get; set; }
    }
}
