//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public Supplier()
        {
            this.WarehouseIOs = new HashSet<WarehouseIO>();
        }
    
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ICollection<WarehouseIO> WarehouseIOs { get; set; }
    }
}
