//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateDemo
    {
        public string TemplateName { get; set; }
        public string Domain { get; set; }
        public string ImageName { get; set; }
        public bool IsPublished { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UpdateByUser { get; set; }
        public string DemoName { get; set; }
    
        public virtual Template Template { get; set; }
    }
}
