//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplatePosition
    {
        public TemplatePosition()
        {
            this.ThirdParties = new HashSet<ThirdParty>();
        }
    
        public string PositionName { get; set; }
        public string TemplateName { get; set; }
        public string Summary { get; set; }
    
        public virtual ICollection<ThirdParty> ThirdParties { get; set; }
        public virtual Template Template { get; set; }
    }
}
