//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public decimal Value { get; set; }
        public bool IsPercent { get; set; }
        public int Quantity { get; set; }
        public Nullable<System.DateTime> EffectDate { get; set; }
        public Nullable<System.DateTime> ExpirDate { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
