//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using log4net;

namespace Web.Data
{
    public partial class WebEntities : DbContext
    {
    	/// <summary>
        ///     The log.
        /// </summary>
        protected static readonly ILog log = LogManager.GetLogger(typeof(WebEntities));
    
        public WebEntities(string connectionString) :
            base(new System.Data.Entity.Core.Objects.ObjectContext(new System.Data.Entity.Core.EntityClient.EntityConnection(connectionString), true),true)
        {
    		base.Database.Log = s => log.Info(s);
    
    		(this as IObjectContextAdapter).ObjectContext.DefaultContainerName = "WebEntities";
    		this.Configuration.ProxyCreationEnabled = false;
    		this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Company> Companies { get; set; }
        public DbSet<CompanyAddress> CompanyAddresses { get; set; }
        public DbSet<CompanyDomain> CompanyDomains { get; set; }
        public DbSet<CompanyLanguage> CompanyLanguages { get; set; }
        public DbSet<CompanyTemplate> CompanyTemplates { get; set; }
        public DbSet<CompanyUser> CompanyUsers { get; set; }
        public DbSet<ConfigAccessTrade> ConfigAccessTrades { get; set; }
        public DbSet<ConfigGHN> ConfigGHNs { get; set; }
        public DbSet<ConfigGHTK> ConfigGHTKs { get; set; }
        public DbSet<ConfigMemberPoint> ConfigMemberPoints { get; set; }
        public DbSet<ConfigOnePay> ConfigOnePays { get; set; }
        public DbSet<ThirdParty> ThirdParties { get; set; }
        public DbSet<WebConfig> WebConfigs { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<CustomerAddress> CustomerAddresses { get; set; }
        public DbSet<CustomerPoint> CustomerPoints { get; set; }
        public DbSet<Article> Articles { get; set; }
        public DbSet<ArticleLanguage> ArticleLanguages { get; set; }
        public DbSet<ArticleLink> ArticleLinks { get; set; }
        public DbSet<ArticleRelatied> ArticleRelatieds { get; set; }
        public DbSet<BanIP> BanIPs { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<CategoryLanguage> CategoryLanguages { get; set; }
        public DbSet<CategoryType> CategoryTypes { get; set; }
        public DbSet<Item> Items { get; set; }
        public DbSet<ItemComment> ItemComments { get; set; }
        public DbSet<ItemImage> ItemImages { get; set; }
        public DbSet<ItemLike> ItemLikes { get; set; }
        public DbSet<ItemView> ItemViews { get; set; }
        public DbSet<ItemVote> ItemVotes { get; set; }
        public DbSet<Language> Languages { get; set; }
        public DbSet<Menu> Menus { get; set; }
        public DbSet<MenuShortcut> MenuShortcuts { get; set; }
        public DbSet<SEO> SEOs { get; set; }
        public DbSet<SupportOnline> SupportOnlines { get; set; }
        public DbSet<SupportOnlineType> SupportOnlineTypes { get; set; }
        public DbSet<TB_ThongKe> TB_ThongKe { get; set; }
        public DbSet<File> Files { get; set; }
        public DbSet<FileDocument> FileDocuments { get; set; }
        public DbSet<CategoryFix> CategoryFixes { get; set; }
        public DbSet<CategoryMap> CategoryMaps { get; set; }
        public DbSet<District> Districts { get; set; }
        public DbSet<Province> Provinces { get; set; }
        public DbSet<Ward> Wards { get; set; }
        public DbSet<Attribute> Attributes { get; set; }
        public DbSet<AttributeCategory> AttributeCategories { get; set; }
        public DbSet<AttributeValue> AttributeValues { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<ProductAddOn> ProductAddOns { get; set; }
        public DbSet<ProductAttribute> ProductAttributes { get; set; }
        public DbSet<ProductColor> ProductColors { get; set; }
        public DbSet<ProductGroupon> ProductGroupons { get; set; }
        public DbSet<ProductPrice> ProductPrices { get; set; }
        public DbSet<Module> Modules { get; set; }
        public DbSet<ModuleConfig> ModuleConfigs { get; set; }
        public DbSet<ModuleConfigLanguage> ModuleConfigLanguages { get; set; }
        public DbSet<ModuleConfigParam> ModuleConfigParams { get; set; }
        public DbSet<ModuleParam> ModuleParams { get; set; }
        public DbSet<Template> Templates { get; set; }
        public DbSet<TemplateComponent> TemplateComponents { get; set; }
        public DbSet<TemplateComponentPosition> TemplateComponentPositions { get; set; }
        public DbSet<TemplateConfig> TemplateConfigs { get; set; }
        public DbSet<TemplateDemo> TemplateDemoes { get; set; }
        public DbSet<TemplatePosition> TemplatePositions { get; set; }
        public DbSet<TemplateSkin> TemplateSkins { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<OrderProduct> OrderProducts { get; set; }
        public DbSet<OrderTransaction> OrderTransactions { get; set; }
        public DbSet<Supplier> Suppliers { get; set; }
        public DbSet<Voucher> Vouchers { get; set; }
        public DbSet<WarehouseIO> WarehouseIOs { get; set; }
        public DbSet<WarehouseIOColection> WarehouseIOColections { get; set; }
    }
}
