//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebEntities : DbContext
    {
        public WebEntities(string connectionString)
            : base(new System.Data.Entity.Core.Objects.ObjectContext(new System.Data.Entity.Core.EntityClient.EntityConnection(connectionString), true), true)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<CompanyAddress> CompanyAddresses { get; set; }
        public virtual DbSet<CompanyDomain> CompanyDomains { get; set; }
        public virtual DbSet<CompanyLanguage> CompanyLanguages { get; set; }
        public virtual DbSet<CompanyTemplate> CompanyTemplates { get; set; }
        public virtual DbSet<CompanyUser> CompanyUsers { get; set; }
        public virtual DbSet<ConfigAccessTrade> ConfigAccessTrades { get; set; }
        public virtual DbSet<ConfigGHN> ConfigGHNs { get; set; }
        public virtual DbSet<ConfigGHTK> ConfigGHTKs { get; set; }
        public virtual DbSet<ConfigMemberPoint> ConfigMemberPoints { get; set; }
        public virtual DbSet<ConfigOnePay> ConfigOnePays { get; set; }
        public virtual DbSet<ThirdParty> ThirdParties { get; set; }
        public virtual DbSet<WebConfig> WebConfigs { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomerAddress> CustomerAddresses { get; set; }
        public virtual DbSet<CustomerPoint> CustomerPoints { get; set; }
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<ArticleLanguage> ArticleLanguages { get; set; }
        public virtual DbSet<ArticleLink> ArticleLinks { get; set; }
        public virtual DbSet<ArticleRelatied> ArticleRelatieds { get; set; }
        public virtual DbSet<BanIP> BanIPs { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<CategoryLanguage> CategoryLanguages { get; set; }
        public virtual DbSet<CategoryType> CategoryTypes { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<ItemComment> ItemComments { get; set; }
        public virtual DbSet<ItemImage> ItemImages { get; set; }
        public virtual DbSet<ItemLike> ItemLikes { get; set; }
        public virtual DbSet<ItemView> ItemViews { get; set; }
        public virtual DbSet<ItemVote> ItemVotes { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<MenuShortcut> MenuShortcuts { get; set; }
        public virtual DbSet<SEO> SEOs { get; set; }
        public virtual DbSet<SupportOnline> SupportOnlines { get; set; }
        public virtual DbSet<SupportOnlineType> SupportOnlineTypes { get; set; }
        public virtual DbSet<TB_ThongKe> TB_ThongKe { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<FileDocument> FileDocuments { get; set; }
        public virtual DbSet<CategoryFix> CategoryFixes { get; set; }
        public virtual DbSet<CategoryMap> CategoryMaps { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<Ward> Wards { get; set; }
        public virtual DbSet<Attribute> Attributes { get; set; }
        public virtual DbSet<AttributeCategory> AttributeCategories { get; set; }
        public virtual DbSet<AttributeValue> AttributeValues { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductAddOn> ProductAddOns { get; set; }
        public virtual DbSet<ProductAttribute> ProductAttributes { get; set; }
        public virtual DbSet<ProductColor> ProductColors { get; set; }
        public virtual DbSet<ProductGroupon> ProductGroupons { get; set; }
        public virtual DbSet<ProductPrice> ProductPrices { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<ModuleConfig> ModuleConfigs { get; set; }
        public virtual DbSet<ModuleConfigLanguage> ModuleConfigLanguages { get; set; }
        public virtual DbSet<ModuleConfigParam> ModuleConfigParams { get; set; }
        public virtual DbSet<ModuleParam> ModuleParams { get; set; }
        public virtual DbSet<Template> Templates { get; set; }
        public virtual DbSet<TemplateComponent> TemplateComponents { get; set; }
        public virtual DbSet<TemplateComponentPosition> TemplateComponentPositions { get; set; }
        public virtual DbSet<TemplateConfig> TemplateConfigs { get; set; }
        public virtual DbSet<TemplateDemo> TemplateDemoes { get; set; }
        public virtual DbSet<TemplatePosition> TemplatePositions { get; set; }
        public virtual DbSet<TemplateSkin> TemplateSkins { get; set; }
        public virtual DbSet<AppInfo> AppInfoes { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<UserAccount> UserAccounts { get; set; }
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderProduct> OrderProducts { get; set; }
        public virtual DbSet<OrderTransaction> OrderTransactions { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<Voucher> Vouchers { get; set; }
        public virtual DbSet<WarehouseIO> WarehouseIOs { get; set; }
        public virtual DbSet<WarehouseIOColection> WarehouseIOColections { get; set; }
    }
}
