//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleConfigParamModel
    {
        /// <summary>
        /// ParamName
        /// </summary>
        public string ID { get; set; }
        public int ModuleId { get; set; }
        public string Value { get; set; }
        public string Type { get; set; }
        public string Summary { get; set; }
        public bool UIProperty { get; set; }
    }
}
