//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleConfigModel
    {
        public ModuleConfigModel()
        {
        }
    
        public int Id { get; set; }
        public string ModuleName { get; set; }
        public string TemplateName { get; set; }
       
        public string ComponentName { get; set; }
        public bool InTemplate { get; set; }
        public string Position { get; set; }
        public string SkinName { get; set; }

        public string LanguageId { get; set; }
        public string Title { get; set; }

        public int Orders { get; set; }
        public bool Publish { get; set; }
        public string Languages { get; set; }

        public int Params { get; set; }
    }
}
