//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateComponentModel
    {
        public string TemplateName { get; set; }
        public string ComponentName { get; set; }
        public string Summary { get; set; }
        public int Positions { get; set; }
    }
}
